version: 0.0.6
env:
  # if you are using venv, you don't need to set `conda_base_path` and `conda_env_name`.
  conda_base_path: "C:/Users/YourUsername/Miniconda3"
  conda_env_name: "hifisampler"
  python_script_path: "./hifiserver.py"
model:
  # Recommended onnx for CPU users.
  vocoder_path: "./pc_nsf_hifigan_44.1k_hop512_128bin_2025.02/model.onnx"
  model_type: "onnx"
  hnsep_model_path: "./hnsep/vr/model_fp16.onnx"
  # GPU users can also try torch model.
  # vocoder_path: "./pc_nsf_hifigan_44.1k_hop512_128bin_2025.02/model.ckpt"
  # model_type: "ckpt"
  # hnsep_model_path: "./hnsep/vr/model.pt"
audio:
  sample_rate: 44100
  win_size: 2048
  hop_size: 512
  origin_hop_size: 128
  n_fft: 2048
  n_mels: 128
  mel_fmin: 40
  mel_fmax: 16000
processing:
  wave_norm: true
  trim_silence: true  # Trim silence for better wave normalization.
  silence_threshold: -52.0  # dB
  loop_mode: true
  peak_limit: 1.0
  fill: 6
performance:
  max_workers: 2  # Number of worker threads. Recommend 2-4.